# Generated by Django 3.0.4 on 2020-05-02 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
